[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shared"
version = "0.1.0"
description = "Shared modules for Moduly microservices"
dependencies = [
    "sqlalchemy>=2.0.0",
    "pydantic>=2.0.0",
    "pgvector",
    "passlib[bcrypt]",
    "python-jose[cryptography]",
    "python-dotenv",
    "cryptography",
    "pydantic-settings"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["shared*"]
