{{- if .Values.sandbox.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moduly.fullname" . }}-sandbox
  labels:
    {{- include "moduly.componentLabels" (dict "component" "sandbox" "context" .) | nindent 4 }}
  annotations:
    {{- with .Values.sandbox.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.sandbox.service.type }}
  ports:
  - port: {{ .Values.sandbox.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "moduly.componentSelectorLabels" (dict "component" "sandbox" "context" .) | nindent 4 }}
{{- end }}
