apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${GF_DATABASE_HOST}:${GF_DATABASE_PORT}
    user: ${GF_DATABASE_USER}
    secureJsonData:
      password: ${GF_DATABASE_PASSWORD}
    jsonData:
      database: ${GF_DATABASE_NAME}
      sslmode: disable
